### base rouuter path
GET http://localhost:3000

### route to get all songs
GET http://localhost:3000/songs

### route to get one song by id
GET  http://localhost:3000/songs/1

### route to post songs
POST http://localhost:3000/songs

### route to update songs
PUT http://localhost:3000/songs/1

### route to delete songs
DELETE http://localhost:3000/songs/1



